# Generated by Django 5.1.6 on 2025-02-21 06:17

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_content_alter_review_product_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='review_tags_gin_idx'),
        ),
    ]
