# Generated by Django 5.1.6 on 2025-02-21 06:23

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_review_tags_gin_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='review',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='review_created_at_idx'),
        ),
    ]
